services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: eventplatform-backend
    expose:
      - "8080"

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    container_name: eventplatform-nginx
    ports:
      - "80:80"
    depends_on:
      - backend