services:
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend.dev
    container_name: eventplatform-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
